name: KeeleCore
version: '${project.version}'
main: dev.joey.keelecore.KeeleCore
api-version: 1.19
authors: [ Joey ]
description: The Core for the keele server
website: https://odionwolf.dev

commands:
  keeleauth:
    description: Commands for Authentication
    aliases:
      - ka
      - kauth


  gamemode:
    description: Changes the players gamemode
    aliases:
      - gm

  time:
    description: Changes the world time
    aliases:
      - tm
      - t